spring.application.name=order-service

server.port=${SERVER_PORT:8085}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

user.service.url=${USER_SERVICE_URL:http://user-service:8084}
address.service.url=${ADDRESS_SERVICE_URL:http://address-service:8087}
cart.service.url=${CART_SERVICE_URL:http://cart-service:8083}
product.service.url=${PRODUCT_SERVICE_URL:http://product-service:8081}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://notification-service:8086}

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
app.kafka.topic.order-created=${KAFKA_ORDER_CREATED_TOPIC:order-created}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
